#pragma once
//From glfw3.h, original copyright notice:
// KeyCodes for StarsSea Input System

#define STARSSEAMOUSEBUTTON1         0
#define STARSSEAMOUSEBUTTON2         1
#define STARSSEAMOUSEBUTTON3         2
#define STARSSEAMOUSEBUTTON4         3
#define STARSSEAMOUSEBUTTON5         4
#define STARSSEAMOUSEBUTTON6         5
#define STARSSEAMOUSEBUTTON7         6
#define STARSSEAMOUSEBUTTON8         7
#define STARSSEAMOUSEBUTTONLAST      STARSSEAMOUSEBUTTON8
#define STARSSEAMOUSEBUTTONLEFT      STARSSEAMOUSEBUTTON1
#define STARSSEAMOUSEBUTTONRIGHT     STARSSEAMOUSEBUTTON2
#define STARSSEAMOUSEBUTTONMIDDLE    STARSSEAMOUSEBUTTON3